web:
  image: droptica/drupal-apache:xdebug
  volumes:
    - ./web:/var/www/html
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: d.dev,www.d.dev
mysql:
  image: mysql:5.6
  volumes:
    - ./docker/database:/var/lib/mysql
    - ./docker/my.conf:/etc/mysql/conf.d/custom.cnf:ro
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - mysql:mysql
  environment:
      VIRTUAL_HOST: phpmyadmin.d.dev

styleguidegulp:
  image: droptica/sc5-styleguide-gulp:latest
  volumes:
    - ./web/themes/d8_bootstrap_subtheme/:/home/theme
  environment:
    VIRTUAL_HOST: styleguide.d.dev, www.styleguide.d.dev